kuploads/urls.py
from django.urls import path

from kuploads import views

app_name = 'kuploads'


urlpatterns = [
    path('exporter/<int:up_setup_pk>/', views.ModelExporterView.as_view(), name='model_exporter'),
    path('form/<int:site_id>/<str:ext_content_str>/<str:slug>/', views.UploadFormView.as_view(), name='upload_form'),
    path('form/<int:up_setup_pk>/', views.UploadFormView.as_view(), name='upload_form'),
    # path(r'^main/(?P<pk>.+)/$', UploadSetupView.as_view(), name='main'),
    path('progress/<int:pk>/', views.UploadProgressView.as_view(), name='progress'),
    path('complete/<int:pk>/', views.UploadCompleteView.as_view(), name='complete'),
    # path(r'^verify/(?P<pk>.+)/$', UploadVerifyView.as_view(), name='verify'),
    path('generator/<int:file_pk>/<int:sheet_index>/', views.UploadGeneratorView.as_view(), name='generator'),
    # path(r'^complete/(?P<pk>.+)/$', 'upload_complete', name='complete'),
    #
    # path(r'^duplicate-template/(?P<pk>.+)/$', 'duplicate_upload_template', name="duplicate-template"),
    # path(r'^structure/json/$', 'json_upload_structure', name='structure'),
    # path(r'^templates/json/$', 'json_related_templates', name="related-templates"),
    # path('sample-fields/json/', views.json_show_sample_fields, name="sample_fields"),
    # (r'^upload/prepare/$', 'prepare_upload'),
]

kuploads/templates/kuploads/complete.html
{% extends based_template %}
{% load static sekizai_tags pagination_tags %}
{% load display_fields common_tags template_design %}

{% block title %}Upload Complete{% endblock %}


{% block right_content %}
	<h4>Upload Complete</h4>

	{% for x in obj.get_valid_files %}
		{% if x.get_issues.upload_issues %}  
		    {% autopaginate x.get_issues.upload_issues 10 as page_issue %} 
		 
			<div class="module full">
				{% regroup page_issue|dictsort:"row" by row as issues_list %}
				
				<table>
					<caption>
						File: {{ x.original_filename }} |
						Uploaded: {{ x.item_count }} | 
						Info: {{ x.get_issues.upload_issues|length }} 
					</caption> 
					<thead>
						<tr>
							<th>Row</th>
							<th>Info</th>
						</tr>
					</thead>
					<tbody>
						{% for issue in issues_list %}
						<tr>      	
							<td> {{ issue.grouper }} </td>
							<td>
								<table>
								{% for obj in issue.list %}
									<tr>
									<td> {{ obj.desc|safe }} </td>
									</tr> 
								{% endfor %}
								</table>
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table> 
			</div>
			
			 {% paginate %}
		{% else %}
			There were no issues.
		{% endif %} 
	{% endfor %}

	
{% endblock %}

kuploads/templates/kuploads/form.html
{% extends based_template %}
{% load static %}
    
{% block title %}Upload {{ upload_setup|title }}{% endblock %}


{% block right_content %}
<h4>Upload: {{ upload_setup }}</h4>

<div class="row">

	<div class="col-md-9">
		<form action="" method="post" id="postform" enctype="multipart/form-data">
			{% csrf_token %}


			<table class="table table-bordered">
				<caption>Form</caption>
				{{ form.as_table }}
				<tr>
					<td></td>
					<td>
						<input class="btn btn-primary btn-sm" type="submit" value="Upload" />
					</td>
				</tr>

			</table>

		</form>
	</div>

	<div class="col-md-3">
		<table class="table table-bordered ">
			<caption>Help</caption>
			<tr>
				<td>
					1. Download sample file to see format expected for upload. <br />
					<a href='{% url "kuploads:model_exporter" upload_setup.pk %}'
					   class="btn btn-outline-primary btn-sm text-center">Download Sample File</a>
				</td>
			</tr>

		</table>
	</div>

</div>

	<div class="module full">

	</div>

{% endblock %}

kuploads/templates/kuploads/progress.html
{% extends based_template %}
{% load static sekizai_tags %}

{% block title %}Upload: Progress{% endblock %}

{% block right_content %}

	<h4>Upload Progress</h4>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th style="width: 100px">Number</th>
				<th class="w-100">Name</th>
			</tr>
		</thead>
		<tbody>
		{% for file_dt in sheet_info %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td>
				<h6>{{ file_dt.file.original_filename }} </h6>
				{% for sheet in file_dt.sheets %}
				<div class="d-flex">
					<div class="ml-3">
						<p>{{ sheet.name }}</p>
					</div>
					<div class="ml-3 w-75 progress">
						 <div id="{{ file_dt.file.pk }}_{{ sheet.sort }}_progress_bar" class="progress-bar"
							  role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
							 0
						 </div>
					</div>
				</div>
				{% endfor %}
			</td>
		</tr>
		{% endfor %}
		</tbody>
	</table>

	<div class="card" id="upload_complete_box" style="display: none">
		<div class="card-body text-center text-success">
			Upload completed successfully
		</div>
	</div>

	{% addtoblock "js" %}
		<script src='{% static "kuploads/js/ajaxq.js" %}?v=0.1' type="text/javascript"></script>

		<script type="text/javascript">
			$(document).ready(function() {
				get_progress();
			});

			function get_progress(){
				{% for file_dt in sheet_info %}
				{% for sheet in file_dt.sheets %}
					for (i=1; i<={{ sheet.set_numbers }}; i++){
						var url = '{% url "kuploads:generator" file_dt.file.pk sheet.sort %}';
						url += '?progress=' + i;
						$.ajaxq ("uploader", {
							url: url,
							//cache: true,
							success: function(data) {
								var elem_progress = $("#{{ file_dt.file.pk }}_{{ sheet.sort }}_progress_bar");
								// var percent_val = data.progress + '%';
								elem_progress.html(data.complete_percent_value + '%');
								elem_progress.css('width', data.complete_percent_value + '%');
								elem_progress.attr('aria-valuenow', data.complete_percent_value);

								{% if forloop.last %}
									if (data.complete_is_completed == true){
										$("#upload_complete_box").css('display', 'block');
										complete_url = '{% url "kuploads:complete" object.pk %}';
										window.location.replace(complete_url);
									}
								{% endif %}
							}
						});
					}
				{% endfor %}
				{% endfor %}
			}
		</script>
	{% endaddtoblock %}

{% endblock %} 